[package]
name = "Insecure_temporary_file"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tempfile = "3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
